### PR TITLE
I changed `dontListen` so that it can be called in the callbacks without an error

### PR DESCRIPTION
**Pull request by davidabrahams**
Please test this before merging it. All this pull request really does is updates the text on the button :+1:

### CODE REVIEW

**Comment by davidabrahams** [comment]
@nmohamed I added calls to updateListeningInndicator and removed the extraneous calls to dontListen. Can we merge this? @LucyWilcox @YuzhongHuang

**Comment by nmohamed** [comment]
could we remove `isListening = false` in 144 and 156 and put it in once at the top of `updateListeningIndicator()` method?

**Comment by davidabrahams** [comment]
No, because updateListeningIndicator also gets called when you start listening, in which case isListening=True

**Comment by nmohamed** [comment]
oh right.
okay, everything looks good - i didn't test it yet but since it's just changing the indicator i don't think things are going to break :poodle:

**Comment by davidabrahams** [comment]
Sure. Have you tested the current master branch? If yes, then I think we can just merge in these changes since I barely changed anything.

**Comment by nmohamed** [comment]
since the last pull was from speech-button-fix2, which does work, i think this is fine to merge.

**Comment by davidabrahams** [comment]
K swag merging

**Pull request merged**
