### PR TITLE
Comments algorithm

### PR DESCRIPTION
**Pull request by YuzhongHuang**
- Fix the filtering issue(already closed) by adding i-- after .remove(i)
- Add randomness to response
- Separate response choosing and response filtering functions

### CODE REVIEW

**Comment by davidabrahams** [comment]
This also seems fine to me. Right now we're just picking a random "valid" comment, this should definitely be improved in the future (I think I'm the one who's doing it?) Just wanted to make sure we were on the same page on that.

**Comment by nmohamed** [comment]
Isn't it okay to pick a random valid comment, out of all the best possible answers? I thought we were doing that so you don't get the same answer when asking a question again

**Comment by nmohamed** [comment]
Anyway, I'm good with merging

**Comment by YuzhongHuang** [comment]
So I searched online about computer humor algorithm. But there isn't any on the internet, since humor is contextual and hard to catch. So I image doing that would be pretty hard. I just leave it later if we are interested and have time.

There are a lot of sentiment analysis APIs, but I don't know are they helpful for our purpose.

**Comment by davidabrahams** [comment]
I think we're going to do it based on upvotes. I'll implement that most likely when I get back to Olin.

**Comment by LucyWilcox** [comment]
I think David's right on the upvote thing. Should we merge this for now? Or close it instead?

**Comment by nmohamed** [comment]
can merge!

**Pull request merged**
